ARG DOCKER_REPO_URL
ARG docker_repo_url=$DOCKER_REPO_URL
ARG CI_PROJECT_NAME
ARG base_project_name=$CI_PROJECT_NAME
FROM ${docker_repo_url}${base_project_name}/minio__minio--release_2024-02-24t17-11-14z