name: Create all jobs

on:
  workflow_dispatch: # or workflow_call
    #inputs:
    #  docker-25:
    #    SERVICE_NAME: "docker-25"
    #    DEPENDS_ON: "docker--25"

jobs:
  #call-workflow:
  #  strategy:
  #    matrix:
  #      services: [ {SERVICE_NAME: "docker-25", DEPENDS_ON: "docker--25" } ]
  #  uses: ./.github/workflows/githubci.yml
  #  secrets: inherit
  #  with:
  #    SERVICE_NAME: ${{ matrix.services.SERVICE_NAME }}
  #    DEPENDS_ON: ${{ matrix.services.DEPENDS_ON }}
    create-workflow:
      runs-on:
        - self-hosted
      steps:
        - uses: actions/checkout@v4
          with:
            token: ${{ secrets.WORKFLOW_TOKEN }}
        - run: jsonnet -S .github/workflows/a.jsonnet > .github/workflows/a.yml
        #- uses: ./.github/workflows/a.yml@main
        - name: GIT commit and push all changed files
          env:
            CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
            CI_COMMIT_AUTHOR: Continuous Integration
          run: |
            git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
            git config --global user.email "osagrigoriy@mail.ru"
            git add .github/workflows/a.yml
            git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push