name: Create all jobs

on:
  workflow_dispatch: # or workflow_call
    inputs:
      docker-25:
        SERVICE_NAME: "docker-25"
        DEPENDS_ON: "docker--25"

jobs:
  call-workflow:
    strategy:
      matrix:
        services: [ "${{ inputs.docker-25 }}" ]
    uses: ./.github/workflows/githubci.yml
    secrets: inherit
    with:
      SERVICE_NAME: ${{ matrix.services.inputs.SERVICE_NAME }}
      DEPENDS_ON: ${{ matrix.DEPENDS_ON }}