name: Create all jobs

on:
  workflow_dispatch: # or workflow_call
    services:
      docker-25:
        SERVICE_NAME: "docker-25"
        DEPENDS_ON: "docker--25"
env:
  DOCKER_REPO_PASSWORD: ${{ secrets.DOCKER_REPO_PASSWORD }}
  DOCKER_REPO_USERNAME: ${{ secrets.DOCKER_REPO_USERNAME }}
jobs:
  call-workflow:
    strategy:
      matrix:
        services: [ "${{ inputs.docker-25 }}" ]
    uses: ./.github/workflows/githubci.yml
    with:
      SERVICE_NAME: ${{ matrix.services.SERVICE_NAME }}
      DEPENDS_ON: ${{ matrix.services.DEPENDS_ON }}
      DOCKER_REPO_PASSWORD: $DOCKER_REPO_PASSWORD
      DOCKER_REPO_USERNAME: $DOCKER_REPO_USERNAME