name: Create all jobs

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/**'
      - '!.github/workflows/generated-config.yml'

jobs:
    create-workflow:
      uses: sea-ls/Pipe/PipelineGeneration.github-ci.yml@main
      secrets: inherit