"env":
  "CI_PROJECT_NAME": "${{ github.event.repository.name }}"
  "DOCKER_REPO_PASSWORD": "${{ secrets.DOCKER_REPO_PASSWORD }}"
  "DOCKER_REPO_URL": "${{ vars.DOCKER_REPO_URL }}"
  "DOCKER_REPO_URL_LOGIN": "${{ vars.DOCKER_REPO_URL_LOGIN }}"
  "DOCKER_REPO_USERNAME": "${{ secrets.DOCKER_REPO_USERNAME }}"
"jobs":
  "builder-jammy-base-0_4_278":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/builder-jammy-base-0.4.278:latest"
      "SERVICE_NAME": "builder-jammy-base-0.4.278"
    "if": "${{ github.event.inputs.build == 'builder-jammy-base-0.4.278' || (needs.changes.outputs.builder-jammy-base-0.4.278 == 'true' || 'needs.changes.outputs.paketobuildpacks__builder-jammy-base--0.4.278' == 'true') || ( github.event.inputs.build == 'paketobuildpacks__builder-jammy-base--0.4.278' ) && always() }}"
    "needs":
      - "changes"
      - "paketobuildpacks__builder-jammy-base--0_4_278"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo builder-jammy-base-0.4.278"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "changes":
    "if": "${{ github.event.inputs.build == null}}"
    "outputs":
      "builder-jammy-base-0.4.278": "${{ 'steps.filter.outputs.builder-jammy-base-0.4.278' }}"
      "docker--25": "${{ 'steps.filter.outputs.docker--25' }}"
      "docker-25": "${{ 'steps.filter.outputs.docker-25' }}"
      "keycloak-23.0": "${{ 'steps.filter.outputs.keycloak-23.0' }}"
      "keycloak__keycloak--23.0": "${{ 'steps.filter.outputs.keycloak__keycloak--23.0' }}"
      "minio-release_2024-04-06t05-26-02z": "${{ 'steps.filter.outputs.minio-release_2024-04-06t05-26-02z' }}"
      "minio__minio--release_2024-04-06t05-26-02z": "${{ 'steps.filter.outputs.minio__minio--release_2024-04-06t05-26-02z' }}"
      "paketobuildpacks__builder-jammy-base--0.4.278": "${{ 'steps.filter.outputs.paketobuildpacks__builder-jammy-base--0.4.278' }}"
      "paketobuildpacks__run-jammy-base--0.1.105": "${{ 'steps.filter.outputs.paketobuildpacks__run-jammy-base--0.1.105' }}"
      "postgres--12-alpine": "${{ 'steps.filter.outputs.postgres--12-alpine' }}"
      "postgres-12-alpine": "${{ 'steps.filter.outputs.postgres-12-alpine' }}"
      "run-jammy-base-0.1.105": "${{ 'steps.filter.outputs.run-jammy-base-0.1.105' }}"
    "permissions":
      "pull-requests": "read"
    "runs-on":
      - "self-hosted"
    "steps":
      - "id": "filter"
        "uses": "dorny/paths-filter@v2"
        "with":
          "filters": "\"builder-jammy-base-0.4.278\":\n- \"builder-jammy-base-0.4.278/**\"\n\"docker--25\":\n- \"./init/docker--25/**\"\n\"docker-25\":\n- \"docker-25/**\"\n\"keycloak-23.0\":\n- \"keycloak-23.0/**\"\n\"keycloak__keycloak--23.0\":\n- \"./init/keycloak__keycloak--23.0/**\"\n\"minio-release_2024-04-06t05-26-02z\":\n- \"minio-release_2024-04-06t05-26-02z/**\"\n\"minio__minio--release_2024-04-06t05-26-02z\":\n- \"./init/minio__minio--release_2024-04-06t05-26-02z/**\"\n\"paketobuildpacks__builder-jammy-base--0.4.278\":\n- \"./init/paketobuildpacks__builder-jammy-base--0.4.278/**\"\n\"paketobuildpacks__run-jammy-base--0.1.105\":\n- \"./init/paketobuildpacks__run-jammy-base--0.1.105/**\"\n\"postgres--12-alpine\":\n- \"./init/postgres--12-alpine/**\"\n\"postgres-12-alpine\":\n- \"postgres-12-alpine/**\"\n\"run-jammy-base-0.1.105\":\n- \"run-jammy-base-0.1.105/**\""
  "docker--25":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/docker--25:latest"
      "SERVICE_NAME": "docker--25"
    "if": "${{ github.event.inputs.build == 'docker--25' || 'needs.changes.outputs.docker--25' == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo docker--25"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "docker-25":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/docker-25:latest"
      "SERVICE_NAME": "docker-25"
    "if": "${{ github.event.inputs.build == 'docker-25' || (needs.changes.outputs.docker-25 == 'true' || 'needs.changes.outputs.docker--25' == 'true') || ( github.event.inputs.build == 'docker--25' ) && always() }}"
    "needs":
      - "changes"
      - "docker--25"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo docker-25"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "keycloak-23_0":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/keycloak-23.0:latest"
      "SERVICE_NAME": "keycloak-23.0"
    "if": "${{ github.event.inputs.build == 'keycloak-23.0' || (needs.changes.outputs.keycloak-23.0 == 'true' || 'needs.changes.outputs.keycloak__keycloak--23.0' == 'true') || ( github.event.inputs.build == 'keycloak__keycloak--23.0' ) && always() }}"
    "needs":
      - "changes"
      - "keycloak__keycloak--23_0"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo keycloak-23.0"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "keycloak__keycloak--23_0":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/keycloak__keycloak--23.0:latest"
      "SERVICE_NAME": "keycloak__keycloak--23.0"
    "if": "${{ github.event.inputs.build == 'keycloak__keycloak--23.0' || 'needs.changes.outputs.keycloak__keycloak--23.0' == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo keycloak__keycloak--23.0"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "minio-release_2024-04-06t05-26-02z":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/minio-release_2024-04-06t05-26-02z:latest"
      "SERVICE_NAME": "minio-release_2024-04-06t05-26-02z"
    "if": "${{ github.event.inputs.build == 'minio-release_2024-04-06t05-26-02z' || (needs.changes.outputs.minio-release_2024-04-06t05-26-02z == 'true' || 'needs.changes.outputs.minio__minio--release_2024-04-06t05-26-02z' == 'true') || ( github.event.inputs.build == 'minio__minio--release_2024-04-06t05-26-02z' ) && always() }}"
    "needs":
      - "changes"
      - "minio__minio--release_2024-04-06t05-26-02z"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo minio-release_2024-04-06t05-26-02z"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "minio__minio--release_2024-04-06t05-26-02z":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/minio__minio--release_2024-04-06t05-26-02z:latest"
      "SERVICE_NAME": "minio__minio--release_2024-04-06t05-26-02z"
    "if": "${{ github.event.inputs.build == 'minio__minio--release_2024-04-06t05-26-02z' || 'needs.changes.outputs.minio__minio--release_2024-04-06t05-26-02z' == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo minio__minio--release_2024-04-06t05-26-02z"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "paketobuildpacks__builder-jammy-base--0_4_278":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/paketobuildpacks__builder-jammy-base--0.4.278:latest"
      "SERVICE_NAME": "paketobuildpacks__builder-jammy-base--0.4.278"
    "if": "${{ github.event.inputs.build == 'paketobuildpacks__builder-jammy-base--0.4.278' || 'needs.changes.outputs.paketobuildpacks__builder-jammy-base--0.4.278' == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo paketobuildpacks__builder-jammy-base--0.4.278"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "paketobuildpacks__run-jammy-base--0_1_105":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/paketobuildpacks__run-jammy-base--0.1.105:latest"
      "SERVICE_NAME": "paketobuildpacks__run-jammy-base--0.1.105"
    "if": "${{ github.event.inputs.build == 'paketobuildpacks__run-jammy-base--0.1.105' || 'needs.changes.outputs.paketobuildpacks__run-jammy-base--0.1.105' == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo paketobuildpacks__run-jammy-base--0.1.105"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "postgres--12-alpine":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/postgres--12-alpine:latest"
      "SERVICE_NAME": "postgres--12-alpine"
    "if": "${{ github.event.inputs.build == 'postgres--12-alpine' || 'needs.changes.outputs.postgres--12-alpine' == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo postgres--12-alpine"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "postgres-12-alpine":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/postgres-12-alpine:latest"
      "SERVICE_NAME": "postgres-12-alpine"
    "if": "${{ github.event.inputs.build == 'postgres-12-alpine' || (needs.changes.outputs.postgres-12-alpine == 'true' || 'needs.changes.outputs.postgres--12-alpine' == 'true') || ( github.event.inputs.build == 'postgres--12-alpine' ) && always() }}"
    "needs":
      - "changes"
      - "postgres--12-alpine"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo postgres-12-alpine"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "run-jammy-base-0_1_105":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/run-jammy-base-0.1.105:latest"
      "SERVICE_NAME": "run-jammy-base-0.1.105"
    "if": "${{ github.event.inputs.build == 'run-jammy-base-0.1.105' || (needs.changes.outputs.run-jammy-base-0.1.105 == 'true' || 'needs.changes.outputs.paketobuildpacks__run-jammy-base--0.1.105' == 'true') || ( github.event.inputs.build == 'paketobuildpacks__run-jammy-base--0.1.105' ) && always() }}"
    "needs":
      - "changes"
      - "paketobuildpacks__run-jammy-base--0_1_105"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo run-jammy-base-0.1.105"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
"name": "Create and publish a Docker image"
"on":
  "pull_request":
    "types":
      - "closed"
  "push":
    "paths-ignore":
      - ".github/**"
  "workflow_dispatch":
    "inputs":
      "build":
        "description": "Who to build"
        "options":
          - "docker-25"
          - "minio-release_2024-04-06t05-26-02z"
          - "postgres-12-alpine"
          - "builder-jammy-base-0.4.278"
          - "run-jammy-base-0.1.105"
          - "keycloak-23.0"
          - "docker--25"
          - "keycloak__keycloak--23.0"
          - "minio__minio--release_2024-04-06t05-26-02z"
          - "paketobuildpacks__builder-jammy-base--0.4.278"
          - "paketobuildpacks__run-jammy-base--0.1.105"
          - "postgres--12-alpine"
        "type": "choice"
