"env":
  "CI_PROJECT_NAME": "${{ github.event.repository.name }}"
  "DOCKER_REPO_PASSWORD": "${{ secrets.DOCKER_REPO_PASSWORD }}"
  "DOCKER_REPO_URL": "${{ vars.DOCKER_REPO_URL }}"
  "DOCKER_REPO_URL_LOGIN": "${{ vars.DOCKER_REPO_URL_LOGIN }}"
  "DOCKER_REPO_USERNAME": "${{ secrets.DOCKER_REPO_USERNAME }}"
"jobs":
  "changes":
    "outputs":
      "docker--25": "${{ steps.filter.outputs.docker--25 }}"
      "docker-25": "${{ steps.filter.outputs.docker-25 }}"
      "minio--release_2024-02-24T17-11-14Z": "${{ steps.filter.outputs.minio--release_2024-02-24T17-11-14Z }}"
      "minio-release_2024-02-24T17-11-14Z": "${{ steps.filter.outputs.minio-release_2024-02-24T17-11-14Z }}"
    "permissions":
      "pull-requests": "read"
    "runs-on":
      - "self-hosted"
    "steps":
      - "id": "filter"
        "uses": "dorny/paths-filter@v3"
        "with":
          "filters": "\"docker--25\":\n- \"./init/docker--25/**\"\n\"docker-25\":\n- \"docker-25/**\"\n\"minio--release_2024-02-24T17-11-14Z\":\n- \"minio--release_2024-02-24T17-11-14Z/**\"\n\"minio-release_2024-02-24T17-11-14Z\":\n- \"./init/minio-release_2024-02-24T17-11-14Z/**\""
  "docker--25":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/docker--25:latest"
      "SERVICE_NAME": "docker--25"
    "if": "${{ always() }} && ${{ needs.changes.outputs.docker--25 == 'true' }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo docker--25"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "docker-25":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/docker-25:latest"
      "SERVICE_NAME": "docker-25"
    "if": "${{ always() }} && {{ needs.changes.outputs.docker-25 == 'true' }}"
    "needs":
      - "changes"
      - "docker--25"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo docker-25"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "minio--release_2024-02-24T17-11-14Z":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/minio--release_2024-02-24T17-11-14Z:latest"
      "SERVICE_NAME": "minio--release_2024-02-24T17-11-14Z"
    "if": "${{ always() }} && {{ needs.changes.outputs.minio--release_2024-02-24T17-11-14Z == 'true' }}"
    "needs":
      - "changes"
      - "minio-release_2024-02-24T17-11-14Z"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo minio--release_2024-02-24T17-11-14Z"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "minio-release_2024-02-24T17-11-14Z":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/minio-release_2024-02-24T17-11-14Z:latest"
      "SERVICE_NAME": "minio-release_2024-02-24T17-11-14Z"
    "if": "${{ always() }} && ${{ needs.changes.outputs.minio-release_2024-02-24T17-11-14Z == 'true' }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo minio-release_2024-02-24T17-11-14Z"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
"name": "Create and publish a Docker image"
"on":
  "push":
    "paths-ignore":
      - ".github/**"
  "workflow_run":
    "types":
      - "completed"
    "workflows":
      - "Create all jobs"
