"env":
  "CI_PROJECT_NAME": "${{ github.event.repository.name }}"
  "DOCKER_REPO_PASSWORD": "${{ secrets.DOCKER_REPO_PASSWORD }}"
  "DOCKER_REPO_URL": "${{ vars.DOCKER_REPO_URL }}"
  "DOCKER_REPO_URL_LOGIN": "${{ vars.DOCKER_REPO_URL_LOGIN }}"
  "DOCKER_REPO_USERNAME": "${{ secrets.DOCKER_REPO_USERNAME }}"
"jobs":
  "builder-jammy-base-0_4_278":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/builder-jammy-base-0_4_278:latest"
      "SERVICE_NAME": "builder-jammy-base-0_4_278"
    "if": "${{ github.event.inputs.build == 'builder-jammy-base-0_4_278' || (needs.changes.outputs.builder-jammy-base-0_4_278 == 'true' || needs.changes.outputs.paketobuildpacks__builder-jammy-base--0_4_278 == 'true') || ( github.event.inputs.build == 'paketobuildpacks__builder-jammy-base--0_4_278' ) && always() }}"
    "needs":
      - "changes"
      - "paketobuildpacks__builder-jammy-base--0_4_278"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo builder-jammy-base-0_4_278"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "changes":
    "if": "${{ github.event.inputs.build == null}}"
    "outputs":
      "builder-jammy-base-0_4_278": "${{ steps.filter.outputs.builder-jammy-base-0_4_278 }}"
      "docker--25": "${{ steps.filter.outputs.docker--25 }}"
      "docker-25": "${{ steps.filter.outputs.docker-25 }}"
      'keycloak-24.0': "${{ 'steps.filter.outputs.keycloak-24.0' }}"
      "keycloak__keycloak--24_0": "${{ steps.filter.outputs.keycloak__keycloak--24_0 }}"
      "minio-release_2024-02-24t17-11-14z": "${{ steps.filter.outputs.minio-release_2024-02-24t17-11-14z }}"
      "minio__minio--release_2024-02-24t17-11-14z": "${{ steps.filter.outputs.minio__minio--release_2024-02-24t17-11-14z }}"
      "paketobuildpacks__builder-jammy-base--0_4_278": "${{ steps.filter.outputs.paketobuildpacks__builder-jammy-base--0_4_278 }}"
      "paketobuildpacks__run-jammy-base--0_1_105": "${{ steps.filter.outputs.paketobuildpacks__run-jammy-base--0_1_105 }}"
      "postgres--12-alpine": "${{ steps.filter.outputs.postgres--12-alpine }}"
      "postgres-12-alpine": "${{ steps.filter.outputs.postgres-12-alpine }}"
      "run-jammy-base-0_1_105": "${{ steps.filter.outputs.run-jammy-base-0_1_105 }}"
    "permissions":
      "pull-requests": "read"
    "runs-on":
      - "self-hosted"
    "steps":
      - "id": "filter"
        "uses": "dorny/paths-filter@v2"
        "with":
          "filters": "\"builder-jammy-base-0_4_278\":\n- \"builder-jammy-base-0_4_278/**\"\n\"docker--25\":\n- \"./init/docker--25/**\"\n\"docker-25\":\n- \"docker-25/**\"\n\"keycloak-24.0\":\n- \"keycloak-24.0/**\"\n\"keycloak__keycloak--24_0\":\n- \"./init/keycloak__keycloak--24_0/**\"\n\"minio-release_2024-02-24t17-11-14z\":\n- \"minio-release_2024-02-24t17-11-14z/**\"\n\"minio__minio--release_2024-02-24t17-11-14z\":\n- \"./init/minio__minio--release_2024-02-24t17-11-14z/**\"\n\"paketobuildpacks__builder-jammy-base--0_4_278\":\n- \"./init/paketobuildpacks__builder-jammy-base--0_4_278/**\"\n\"paketobuildpacks__run-jammy-base--0_1_105\":\n- \"./init/paketobuildpacks__run-jammy-base--0_1_105/**\"\n\"postgres--12-alpine\":\n- \"./init/postgres--12-alpine/**\"\n\"postgres-12-alpine\":\n- \"postgres-12-alpine/**\"\n\"run-jammy-base-0_1_105\":\n- \"run-jammy-base-0_1_105/**\""
  "docker--25":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/docker--25:latest"
      "SERVICE_NAME": "docker--25"
    "if": "${{ github.event.inputs.build == 'docker--25' || needs.changes.outputs.docker--25 == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo docker--25"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "docker-25":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/docker-25:latest"
      "SERVICE_NAME": "docker-25"
    "if": "${{ github.event.inputs.build == 'docker-25' || (needs.changes.outputs.docker-25 == 'true' || needs.changes.outputs.docker--25 == 'true') || ( github.event.inputs.build == 'docker--25' ) && always() }}"
    "needs":
      - "changes"
      - "docker--25"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo docker-25"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "keycloak-24.0":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/keycloak-24.0:latest"
      "SERVICE_NAME": "keycloak-24.0"
    "if": "${{ github.event.inputs.build == 'keycloak-24.0' || (needs.changes.outputs.keycloak-24.0 == 'true' || needs.changes.outputs.keycloak__keycloak--24_0 == 'true') || ( github.event.inputs.build == 'keycloak__keycloak--24_0' ) && always() }}"
    "needs":
      - "changes"
      - "keycloak__keycloak--24_0"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo keycloak-24.0"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "keycloak__keycloak--24_0":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/keycloak__keycloak--24_0:latest"
      "SERVICE_NAME": "keycloak__keycloak--24_0"
    "if": "${{ github.event.inputs.build == 'keycloak__keycloak--24_0' || needs.changes.outputs.keycloak__keycloak--24_0 == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo keycloak__keycloak--24_0"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "minio-release_2024-02-24t17-11-14z":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/minio-release_2024-02-24t17-11-14z:latest"
      "SERVICE_NAME": "minio-release_2024-02-24t17-11-14z"
    "if": "${{ github.event.inputs.build == 'minio-release_2024-02-24t17-11-14z' || (needs.changes.outputs.minio-release_2024-02-24t17-11-14z == 'true' || needs.changes.outputs.minio__minio--release_2024-02-24t17-11-14z == 'true') || ( github.event.inputs.build == 'minio__minio--release_2024-02-24t17-11-14z' ) && always() }}"
    "needs":
      - "changes"
      - "minio__minio--release_2024-02-24t17-11-14z"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo minio-release_2024-02-24t17-11-14z"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "minio__minio--release_2024-02-24t17-11-14z":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/minio__minio--release_2024-02-24t17-11-14z:latest"
      "SERVICE_NAME": "minio__minio--release_2024-02-24t17-11-14z"
    "if": "${{ github.event.inputs.build == 'minio__minio--release_2024-02-24t17-11-14z' || needs.changes.outputs.minio__minio--release_2024-02-24t17-11-14z == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo minio__minio--release_2024-02-24t17-11-14z"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "paketobuildpacks__builder-jammy-base--0_4_278":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/paketobuildpacks__builder-jammy-base--0_4_278:latest"
      "SERVICE_NAME": "paketobuildpacks__builder-jammy-base--0_4_278"
    "if": "${{ github.event.inputs.build == 'paketobuildpacks__builder-jammy-base--0_4_278' || needs.changes.outputs.paketobuildpacks__builder-jammy-base--0_4_278 == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo paketobuildpacks__builder-jammy-base--0_4_278"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "paketobuildpacks__run-jammy-base--0_1_105":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/paketobuildpacks__run-jammy-base--0_1_105:latest"
      "SERVICE_NAME": "paketobuildpacks__run-jammy-base--0_1_105"
    "if": "${{ github.event.inputs.build == 'paketobuildpacks__run-jammy-base--0_1_105' || needs.changes.outputs.paketobuildpacks__run-jammy-base--0_1_105 == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo paketobuildpacks__run-jammy-base--0_1_105"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "postgres--12-alpine":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/postgres--12-alpine:latest"
      "SERVICE_NAME": "postgres--12-alpine"
    "if": "${{ github.event.inputs.build == 'postgres--12-alpine' || needs.changes.outputs.postgres--12-alpine == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo postgres--12-alpine"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "postgres-12-alpine":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/postgres-12-alpine:latest"
      "SERVICE_NAME": "postgres-12-alpine"
    "if": "${{ github.event.inputs.build == 'postgres-12-alpine' || (needs.changes.outputs.postgres-12-alpine == 'true' || needs.changes.outputs.postgres--12-alpine == 'true') || ( github.event.inputs.build == 'postgres--12-alpine' ) && always() }}"
    "needs":
      - "changes"
      - "postgres--12-alpine"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo postgres-12-alpine"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "run-jammy-base-0_1_105":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/run-jammy-base-0_1_105:latest"
      "SERVICE_NAME": "run-jammy-base-0_1_105"
    "if": "${{ github.event.inputs.build == 'run-jammy-base-0_1_105' || (needs.changes.outputs.run-jammy-base-0_1_105 == 'true' || needs.changes.outputs.paketobuildpacks__run-jammy-base--0_1_105 == 'true') || ( github.event.inputs.build == 'paketobuildpacks__run-jammy-base--0_1_105' ) && always() }}"
    "needs":
      - "changes"
      - "paketobuildpacks__run-jammy-base--0_1_105"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo run-jammy-base-0_1_105"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
"name": "Create and publish a Docker image"
"on":
  "pull_request":
    "types":
      - "closed"
  "push":
    "paths-ignore":
      - ".github/**"
  "workflow_dispatch":
    "inputs":
      "build":
        "description": "Who to build"
        "options":
          - "docker-25"
          - "minio-release_2024-02-24t17-11-14z"
          - "postgres-12-alpine"
          - "builder-jammy-base-0_4_278"
          - "run-jammy-base-0_1_105"
          - "keycloak-24.0"
          - "docker--25"
          - "keycloak__keycloak--24_0"
          - "minio__minio--release_2024-02-24t17-11-14z"
          - "paketobuildpacks__builder-jammy-base--0_4_278"
          - "paketobuildpacks__run-jammy-base--0_1_105"
          - "postgres--12-alpine"
        "type": "choice"