"env":
  "CI_PROJECT_NAME": "${{ github.event.repository.name }}"
  "DOCKER_REPO_PASSWORD": "${{ secrets.DOCKER_REPO_PASSWORD }}"
  "DOCKER_REPO_URL": "${{ vars.DOCKER_REPO_URL }}"
  "DOCKER_REPO_URL_LOGIN": "${{ vars.DOCKER_REPO_URL_LOGIN }}"
  "DOCKER_REPO_USERNAME": "${{ secrets.DOCKER_REPO_USERNAME }}"
"jobs":
  "changes":
    "outputs":
      "minio-release_2024-02-24t17-11-14z": "${{ steps.filter.outputs.minio-release_2024-02-24t17-11-14z }}"
      "minio__minio--release_2024-02-24t17-11-14z": "${{ steps.filter.outputs.minio__minio--release_2024-02-24t17-11-14z }}"
      "postgres--16": "${{ steps.filter.outputs.postgres--16 }}"
      "postgres-16": "${{ steps.filter.outputs.postgres-16 }}"
    "permissions":
      "pull-requests": "read"
    "runs-on":
      - "self-hosted"
    "steps":
      - "id": "filter"
        "uses": "dorny/paths-filter@v3"
        "with":
          "filters": "\"minio-release_2024-02-24t17-11-14z\":\n- \"minio-release_2024-02-24t17-11-14z/**\"\n\"minio__minio--release_2024-02-24t17-11-14z\":\n- \"./init/minio__minio--release_2024-02-24t17-11-14z/**\"\n\"postgres--16\":\n- \"./init/postgres--16/**\"\n\"postgres-16\":\n- \"postgres-16/**\""
  "minio-release_2024-02-24t17-11-14z":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/minio-release_2024-02-24t17-11-14z:latest"
      "SERVICE_NAME": "minio-release_2024-02-24t17-11-14z"
    "if": "${{inputs.build == minio-release_2024-02-24t17-11-14z || (needs.changes.outputs.minio-release_2024-02-24t17-11-14z == 'true' || needs.changes.outputs.minio__minio--release_2024-02-24t17-11-14z == 'true') && always() }}"
    "needs":
      - "changes"
      - "minio__minio--release_2024-02-24t17-11-14z"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo minio-release_2024-02-24t17-11-14z"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "minio__minio--release_2024-02-24t17-11-14z":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/minio__minio--release_2024-02-24t17-11-14z:latest"
      "SERVICE_NAME": "minio__minio--release_2024-02-24t17-11-14z"
    "if": "${{inputs.build == minio__minio--release_2024-02-24t17-11-14z || needs.changes.outputs.minio__minio--release_2024-02-24t17-11-14z == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo minio__minio--release_2024-02-24t17-11-14z"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "postgres--16":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/postgres--16:latest"
      "SERVICE_NAME": "postgres--16"
    "if": "${{inputs.build == postgres--16 || needs.changes.outputs.postgres--16 == 'true' && always() }}"
    "needs": "changes"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo postgres--16"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME"
      - "run": "docker push $IMAGE"
  "postgres-16":
    "env":
      "IMAGE": "${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/postgres-16:latest"
      "SERVICE_NAME": "postgres-16"
    "if": "${{inputs.build == postgres-16 || (needs.changes.outputs.postgres-16 == 'true' || needs.changes.outputs.postgres--16 == 'true') && always() }}"
    "needs":
      - "changes"
      - "postgres--16"
    "runs-on":
      - "self-hosted"
    "steps":
      - "uses": "actions/checkout@v3"
      - "run": "echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin"
      - "run": "echo postgres-16"
      - "run": "docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME"
      - "run": "docker push $IMAGE"
"name": "Create and publish a Docker image"
"on":
  "push":
    "paths-ignore":
      - ".github/**"
  "workflow_dispatch":
    "inputs":
      "build":
        "description": "Who to build"
        "options":
          - "minio-release_2024-02-24t17-11-14z"
          - "postgres-16"
          - "minio__minio--release_2024-02-24t17-11-14z"
          - "postgres--16"
        "type": "choice"
  "workflow_run":
    "types":
      - "completed"
    "workflows":
      - "Create all jobs"
