name: Create and publish a Docker image

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      DEPENDS_ON:
        required: true
        type: string
  push:
    paths:
      - $SERVICE_NAME
env:
  CI_PROJECT_NAME: ${GITHUB_REPOSITORY#*/}
  IMAGE: ${{ vars.DOCKER_REPO_URL }}${CI_PROJECT_NAME}/${{ inputs.SERVICE_NAME }}:latest

jobs:
  build-dependencies:
    runs-on: [ self-hosted ]
    #   permissions:
    #   contents: read
    #   packages: write

    steps:
      - uses: actions/checkout@v3
      - env:
          DOCKER_REPO_PASSWORD: ${{ secrets.DOCKER_REPO_PASSWORD }}
          DOCKER_REPO_USERNAME: ${{ vars.DOCKER_REPO_USERNAME }}
      - run: "echo $DOCKER_REPO_PASSWORD | docker login ghcr.io -u $DOCKER_REPO_USERNAME --password-stdin"
      - run: pwd
      - run: docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/${{ inputs.DEPENDS_ON }}
      - run: docker push $IMAGE

  build-images:
    runs-on: [ self-hosted ]
    needs: [ build-dependencies ]
   #   permissions:
   #   contents: read
   #   packages: write

    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.DOCKER_REPO_PASSWORD }} | docker login ghcr.io -u ${{ vars.DOCKER_REPO_USERNAME }} --password-stdin
      - run: pwd
      - run: docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./${{ inputs.SERVICE_NAME }}
      - run: docker push $IMAGE
