name: Create and publish a Docker image

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      DEPENDS_ON:
        required: true
        type: string
  push:
    paths:
      - $SERVICE_NAME
env:
  DOCKER_REPO_PASSWORD: ${{ secrets.DOCKER_REPO_PASSWORD }}
  DOCKER_REPO_USERNAME: ${{ secrets.DOCKER_REPO_USERNAME }}
  DOCKER_REPO_URL_LOGIN: ${{ vars.DOCKER_REPO_URL_LOGIN }}
  DOCKER_REPO_URL: ${{ vars.DOCKER_REPO_URL }}
  CI_PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  build-dependencies:
    runs-on: [ self-hosted ]
    #   permissions:
    #   contents: read
    #   packages: write
    env:
      SERVICE_NAME: ${{ inputs.DEPENDS_ON }}
      IMAGE: ${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/${{ env.SERVICE_NAME }}:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin
      - run: echo "${{ inputs.SERVICE_NAME }}"
      - run: docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./init/$SERVICE_NAME
      - run: docker push $IMAGE

  build-images:
    runs-on: [ self-hosted ]
    needs: [ build-dependencies ]
    env:
      SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
      IMAGE: ${{ vars.DOCKER_REPO_URL }}${{ github.event.repository.name }}/${{ env.SERVICE_NAME }}:latest
   #   permissions:
   #   contents: read
   #   packages: write
    steps:
      - uses: actions/checkout@v3
      - run: echo $DOCKER_REPO_PASSWORD | docker login $DOCKER_REPO_URL_LOGIN -u $DOCKER_REPO_USERNAME --password-stdin
      - run: pwd
      - run: docker build --build-arg DOCKER_REPO_URL --build-arg CI_PROJECT_NAME -t $IMAGE ./$SERVICE_NAME
      - run: docker push $IMAGE