name: Create all jobs

on:
  workflow_dispatch: # or workflow_call
    services:
      docker-25:
        SERVICE_NAME: "docker-25"
        DEPENDS_ON: "docker--25"

jobs:
  generate-pipeline:
    runs-on: [ self-hosted ]
    #   permissions:
    #   contents: read
    #   packages: write
    steps:
      - run: pwd
      - run: ls ./.github/workflows/
      - uses: actions/checkout@v3
      - run: jsonnet -S --ext-str branch=develop --ext-str need_bkp=false ./.github/workflows/test.jsonnet > generated-config.yml
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: generated-config.yml
      #    path: generated-config.yml
  process-pipeline:
    runs-on: [ self-hosted ]
    needs: [   generate-pipeline ]
    #   permissions:
    #   contents: read
    #   packages: write
    steps:
    #- uses: actions/download-artifact@v3
    #  with:
    #    name: generated-config.yml
    #    path: generated-config.yml
    - uses: ./.github/workflows/start.yml